### ISSUE TITLE
Scoreboards in use

### ISSUE THREAD

**Issue by Wolfieheart** [Wolfst0rm/ArmorStandEditor-Issues#18]
### Expected behavior

Scoreboards should not be in use when enabling the plugin.

### Observed/Actual behavior

Scoreboards are in use:

```
[13:26:52] [Server thread/ERROR]: Error occurred while enabling ArmorStandEditor v1.18-31 (Is it up to date?)
java.lang.IllegalArgumentException: Team name 'ASLocked' is already in use
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[commons-lang-2.6.jar:2.6]
at org.bukkit.craftbukkit.v1_18_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:167) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.registerScoreboards(ArmorStandEditorPlugin.java:206) ~[?:?]
at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.onEnable(ArmorStandEditorPlugin.java:88) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps/models to reproduce

N/A

### Plugin list

N/A

### Plugin Version

1.18-31

### Server Version

Paper version: CraftBukkit version 3360-Spigot-f65de01-c2e0bbd (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

### Other

Reported on behalf of Starnos on SpigotMC ( https://www.spigotmc.org/members/starnos.387932/ )

asked in the Spigot MC Discord. Got an idea for a fix.

**Comment by Wolfieheart** [comment]
For those that want to test this: https://github.com/Wolfst0rm/ArmorStandEditor/suites/4638820317/artifacts/125713507

Extract and add to Paper/Spigot Server and have fun!
